# Generated by Django 2.1.dev20171216185936 on 2018-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField(max_length=50)),
                ('customer_address', models.TextField(max_length=50)),
                ('customer_contact', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='feederProduct',
            fields=[
                ('feederProduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('feederProduct_name', models.TextField(max_length=25)),
                ('feederProduct_qty', models.IntegerField(max_length=10)),
                ('feederProduct_qtyunit', models.TextField(max_length=5)),
                ('feederProduct_rate', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mProduct',
            fields=[
                ('mProduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('mProduct_name', models.TextField(max_length=50)),
                ('mProduct_qty', models.IntegerField(max_length=10)),
                ('mProduct_qtyunit', models.TextField(max_length=5)),
                ('mProduct_rate', models.IntegerField(max_length=10)),
            ],
        ),
    ]
