# Generated by Django 2.1.dev20171216185936 on 2018-11-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feederproduct',
            name='feederProduct_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feederproduct',
            name='feederProduct_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mproduct',
            name='mProduct_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mproduct',
            name='mProduct_rate',
            field=models.FloatField(),
        ),
    ]
