# Generated by Django 2.1.3 on 2018-11-20 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_auto_20181108_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='mProductSell',
            fields=[
                ('mProductSell_id', models.AutoField(primary_key=True, serialize=False)),
                ('mProductSell_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mProductSell_qty', models.FloatField()),
                ('mProductSell_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='mPurchase',
            fields=[
                ('mPurchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller', models.CharField(max_length=50)),
                ('mPurchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mPurchase_product', models.CharField(choices=[('Cow Milk', 'Cow'), ('Buffalo Milk', 'Buffalo')], max_length=10)),
                ('mPurchase_qty', models.FloatField()),
                ('mPurchase_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='mStock',
            fields=[
                ('mStock_id', models.AutoField(primary_key=True, serialize=False)),
                ('mStock_qty', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='feederproduct',
            name='feederProduct_qty',
        ),
        migrations.RemoveField(
            model_name='feederproduct',
            name='feederProduct_rate',
        ),
        migrations.RemoveField(
            model_name='mproduct',
            name='mProduct_qty',
        ),
        migrations.RemoveField(
            model_name='mproduct',
            name='mProduct_rate',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feederproduct',
            name='feederProduct_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='feederproduct',
            name='feederProduct_qtyunit',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mproduct',
            name='mProduct_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mproduct',
            name='mProduct_qtyunit',
            field=models.CharField(choices=[('kg.', 'Kilogram'), ('ltr', 'Liter'), ('pkt', 'Packet')], default='ltr', max_length=3),
        ),
        migrations.AddField(
            model_name='mstock',
            name='mProduct',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.mProduct'),
        ),
        migrations.AddField(
            model_name='mproductsell',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.Customer'),
        ),
        migrations.AddField(
            model_name='mproductsell',
            name='milk_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.mProduct'),
        ),
    ]
