# Generated by Django 2.1.3 on 2018-11-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0003_auto_20181120_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpurchase',
            name='mPurchase_total',
            field=models.FloatField(default=0),
        ),
    ]
