# Generated by Django 2.1.3 on 2018-11-24 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0004_mpurchase_mpurchase_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpurchase',
            name='mPurchase_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 1, 22, 55, 549050)),
        ),
    ]
