# Generated by Django 2.1.3 on 2018-11-24 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0005_auto_20181125_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpurchase',
            name='mPurchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
