# Generated by Django 2.1.3 on 2018-11-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0006_auto_20181125_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='mProductUnit',
            fields=[
                ('mProductUnit_id', models.AutoField(primary_key=True, serialize=False)),
                ('mProductUnit_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='mproduct',
            name='mProduct_qtyunit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.mProductUnit'),
        ),
    ]
