# Generated by Django 2.1.3 on 2018-11-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0008_auto_20181126_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproduct',
            name='mProduct_qty',
            field=models.FloatField(default=0),
        ),
    ]
