# Generated by Django 2.1.3 on 2018-11-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0009_mproduct_mproduct_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mstock',
            old_name='mProduct',
            new_name='mStock_product',
        ),
    ]
