# Generated by Django 2.1.3 on 2018-11-27 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0010_auto_20181126_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstock',
            name='mStock_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.mProduct'),
        ),
    ]
