# Generated by Django 2.1.3 on 2018-11-27 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0011_auto_20181127_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstock',
            name='mStock_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
