# Generated by Django 2.1.3 on 2018-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0012_mstock_mstock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproductsell',
            name='buyer_name',
            field=models.CharField(default='TBD', max_length=50),
        ),
    ]
