# Generated by Django 2.1.3 on 2018-12-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0014_auto_20181203_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproductsell',
            name='milk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.mProduct'),
        ),
    ]
