# Generated by Django 2.1.3 on 2018-12-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0015_auto_20181203_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproductsell',
            name='mProductSell_qtyunit',
            field=models.CharField(default='TBD', max_length=10),
        ),
    ]
